// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBDemo.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220912155632_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Dependent", b =>
                {
                    b.Property<string>("EmployeeSSN")
                        .HasColumnType("char(9)");

                    b.Property<string>("DependentName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.HasKey("EmployeeSSN", "DependentName");

                    b.ToTable("Dependent");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("char(9)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleInitials")
                        .HasColumnType("varchar(5)");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.HasKey("SSN");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.Dependent", b =>
                {
                    b.HasOne("Model.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
