// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBDemo.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220919122914_CompleteSchema")]
    partial class CompleteSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("char(6)");

                    b.Property<string>("ManagerSSN")
                        .HasColumnType("char(9)");

                    b.Property<DateTime>("ManagerStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Number");

                    b.HasIndex("ManagerSSN");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Model.DepartmentLocation", b =>
                {
                    b.Property<string>("DepartmentNumber")
                        .HasColumnType("char(6)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(20)");

                    b.HasKey("DepartmentNumber", "Location");

                    b.ToTable("DepartmentLocation");
                });

            modelBuilder.Entity("Model.Dependent", b =>
                {
                    b.Property<string>("EmployeeSSN")
                        .HasColumnType("char(9)");

                    b.Property<string>("DependentName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.HasKey("EmployeeSSN", "DependentName");

                    b.ToTable("Dependent");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("char(9)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleInitials")
                        .HasColumnType("varchar(5)");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.HasKey("SSN");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("char(6)");

                    b.Property<string>("DepartmentNumber")
                        .HasColumnType("char(6)");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Number");

                    b.HasIndex("DepartmentNumber");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Model.WorksOn", b =>
                {
                    b.Property<string>("EmployeeSSN")
                        .HasColumnType("char(9)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("char(6)");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeSSN", "ProjectNumber");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("WorksOn");
                });

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.HasOne("Model.Employee", "Manager")
                        .WithMany("ManagedDepartments")
                        .HasForeignKey("ManagerSSN");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Model.DepartmentLocation", b =>
                {
                    b.HasOne("Model.Department", "Department")
                        .WithMany("Locations")
                        .HasForeignKey("DepartmentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Model.Dependent", b =>
                {
                    b.HasOne("Model.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.HasOne("Model.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentNumber");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Model.WorksOn", b =>
                {
                    b.HasOne("Model.Employee", "Employee")
                        .WithMany("Schedule")
                        .HasForeignKey("EmployeeSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Project", "Project")
                        .WithMany("Developers")
                        .HasForeignKey("ProjectNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("ManagedDepartments");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.Navigation("Developers");
                });
#pragma warning restore 612, 618
        }
    }
}
