// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Week_02;

#nullable disable

namespace Week_02.Migrations
{
    [DbContext(typeof(Model.MyContext))]
    [Migration("20250522112446_DepartmentDB")]
    partial class DepartmentDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Week_02.Model+Department", b =>
                {
                    b.Property<Guid>("Dnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mgr_ssn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Mgr_start_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Dnumber");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Week_02.Model+Employee", b =>
                {
                    b.Property<Guid>("Ssn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Bday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dno")
                        .HasColumnType("integer");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Minit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Salary")
                        .HasColumnType("integer");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)");

                    b.Property<int>("Super_ssn")
                        .HasColumnType("integer");

                    b.HasKey("Ssn");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
