// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Week_02;

#nullable disable

namespace Week_02.Migrations
{
    [DbContext(typeof(Model.MyContext))]
    [Migration("20250522114417_RestDB")]
    partial class RestDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Week_02.Model+Department", b =>
                {
                    b.Property<string>("Dnumber")
                        .HasColumnType("text");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mgr_ssn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Mgr_start_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Dnumber");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Week_02.Model+Dependent", b =>
                {
                    b.Property<string>("Essn")
                        .HasColumnType("text");

                    b.Property<string>("Dependen_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Bday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)");

                    b.HasKey("Essn", "Dependen_name");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("Week_02.Model+Dept_Location", b =>
                {
                    b.Property<string>("Dnumber")
                        .HasColumnType("text");

                    b.Property<string>("Dlocation")
                        .HasColumnType("text");

                    b.HasKey("Dnumber", "Dlocation");

                    b.ToTable("Dept_Locations");
                });

            modelBuilder.Entity("Week_02.Model+Employee", b =>
                {
                    b.Property<string>("Ssn")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Bday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Minit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Salary")
                        .HasColumnType("integer");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)");

                    b.Property<string>("Super_ssn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ssn");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Week_02.Model+Project", b =>
                {
                    b.Property<string>("Pnumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dnum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Pnumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Week_02.Model+Works_on", b =>
                {
                    b.Property<string>("Essn")
                        .HasColumnType("text");

                    b.Property<string>("Pno")
                        .HasColumnType("text");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.HasKey("Essn", "Pno");

                    b.ToTable("Works_ons");
                });
#pragma warning restore 612, 618
        }
    }
}
